name: Build and Deploy

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: install python 
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
        name: Update pip
      - uses: pythom -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt